baseurl: "https://rlem-workshop.net/"
title: "International Workshop on Reinforcement Learning for Energy Management in Buildings & Cities (RLEM)"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: ""

params:
  # Conference info
  Name: "First Int'l Workshop on Reinforcement Learning for Energy Management in Buildings & Cities (RLEM)"
  Description: "RLEM brings together researchers and industry practitioners for the advancement of (deep) reinforcement learning (RL) in the built environment as it is applied for managing energy in civil infrastructure systems (energy, water, transportation)."
  Date: " in November 17th 2020"
  #Price: "TBD" # If your event is free, just comment this line
  Venue: "Yokohama, Japan"
  Address: "Online"
  City:  "Yokohama"
  # State: "Quintana"
  Images: ["/img/badge.jpg"]
  GoogleMapsKey: "my-secret-maps-key"
  Registeration: "Eventbite"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - important
    - cfp
    - registration
    - program
    - speakers
    - organization
    #- sponsors
    #- partners
    #- previous
    #- contact

  # Titles which you can translate to other languages
  Titles:
    about: 
        title: "Welcome to RLEM 2020"
        abbr: "About"
    important: 
        title: "Important Dates"
    cfp: 
        title: "Call for Papers"
        abbr: "CFP"
    registration:
        title: "Registration"
    venue: 
        title: "Venue"
    speakers: 
        title: "Keynote Speaker"
        abbr: "Speaker"
    program: 
        title: "Program"
    organization: 
        title: "Organization"
    sponsors: 
        title: "Sponsors"
    partners: 
        title: "Partners"
    # contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: "Register now via BuildSys 2020!"
    link: "http://buildsys.acm.org/2020/"

  # List of Important Days
  Important:
    - name: "Abstract submission"
      date: "August 10, 2020 (AOE)"
      done: true 
    - name: "Paper submission"
      date: "August 17, 2020 (AOE)"
      done: true 
    - name: "Notifications"
      date: "September 21, 2020 (AOE)"
      done: true 
    - name: "Camera Ready"
      date: "October 10, 2020 (AOE)"
      done: true 
    - name: "Workshop date"
      date: "November 17, 2020"
      done: false 

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  #ForkButton:
  #  repository: "https://github.com/jweslley/hugo-conference/"

  # List of Sponsors
  Sponsors:
    - name: "Hugo"
      logo: "/img/hugo.png"
      url: "http://gohugo.io"

  # List of Partners
  Partners:
    - name: "Hugo"
      logo: "/img/hugo.jpg"
      url: "https://gohugo.io"
    - name: "BrazilJS"
      logo: "/img/partner.png"
      url: "http://braziljs.org"

  # List of Organization
  Organization:
    - role: "General"
      chair: true
      member:
        - name: "Zoltan Nagy"
          affiliation: "University of Texas at Austin"
    - role: "Technical Program Committee"
      chair: true
      member:
        - name: "Mario Berges"
          affiliation: "Carnegie Mellon University"
          url: "https://inferlab.org/author/mario-berges/"
        - name: "Bingqing Chen"
          affiliation: "Carnegie Mellon University"
          url: "https://inferlab.org/author/bingqing-chen/"
        - name: "June Young Park"
          url: "http://blog.uta.edu/parkjy/"
          affiliation: "University of Texas at Arlington"
    - role: "Technical Program Committee"
      chair: false
      member:
        - name: "Henning Lange"
          url: "https://amath.washington.edu/people/henning-lange"
          affiliation: "University of Washington"
        - name: "Helia Zandi"
          url: "https://www.ornl.gov/staff-profile/helia-zandi"
          affiliation: "Oak Ridge National Laboratory"
        - name: "Jose Vazquez-Canteli"
          url: "http://nagy.caee.utexas.edu"
          affiliation: "University of Texas at Austin" 
        - name: "Zhe Wang"
          url: "https://buildings.lbl.gov/people/zhe-walter-wang"
          affiliation: "Lawrence Berkeley National Laboratory"
        - name: "Duc Van Le"
          url: ""
          affiliation: "NTU Singapore"
        - name: "Wan Du"
          url: ""
          affiliation: "University of California, Merced"
        - name: "Xin Jin"
          url: ""
          affiliation: "National Renewable Energy Laboratory"
        - name: "Ming Jin"
          url: ""
          affiliation: "University of California, Berkeley"
        - name: "Alex Vlachokostas"
          url: ""
          affiliation: "Pacific Northwest National Laboratory"
        - name: "Hari Prasanna Das"
          url: ""
          affiliation: "University of California, Berkeley"
        - name: "Lucas Spangheer"
          url: ""
          affiliation: "University of California, Berkeley"
        - name: "Kuldeep Kurte"
          url: ""
          affiliation: "Oak Ridge National Laboratory"
        - name: "Ross May"
          url: ""
          affiliation: "Dalarna University"
 #       - name: ""
 #         url: ""
 #         affiliation: ""
          
  # The entire program 
  Program:
    
    - type: "session"
      time: "12:00 - 12:20"
      name: "Opening remarks, by General Chair and TPC Chairs"
      
    - type: "session"
      time: "12:20 - 13:00"
      name: "Keynote: Incorporating robust control guarantees within (deep) reinforcement learning"
    
    - type: "date"
      date: "Session 1: Demanding Response"
      
    - type: "session"
      time: "13:00 - 13:50"
      name: "M.H. Christensen, C. Ernewein, P. Pinson (Technical University of Denmark)—Demand Response through Price-setting Multi-agent Reinforcement Learning"
      link: "https://youtu.be/_f0L313_4xE"
      
    - type: "session"
      name: "K. Kurte, J. Munk, K. Amasyali, O. Kotevska, R. Smith, H. Zandi (Oak Ridge National Laboratory)—Electricity Pricing aware Deep Reinforcement Learning based Intelligent HVAC Control" 
      link: "https://youtu.be/T6s2xdECsrs"
      
    - type: "session"
      name: "A. Kathirgamanathan, K. Twardowski, E. Mangina, D. Finn (University College Dublin)—A Centralised Soft Actor Critic Deep Reinforcement Learning Approach to District Demand Side Management through CityLearn"
      link: "https://youtu.be/mviLSJueV3k"
      
    - type: "session"
      name: "G. Dhamankar, J. Vazquez-Canteli, Z. Nagy (The University of Texas at Austin)—Benchmarking Multi-Agent Deep Reinforcement Learning Algorithms on a Building Energy Demand Coordination Task"
      link: "https://youtu.be/eWlVPKIB23o"
      
    - type: "session"
      name: "Discussion" 
      
    - type: "session"
      time: "13:50 - 14:00"
      name: "Break"  
      
    - type: "date"
      date: "Session 2: Clash of Algorithms"
    
    - type: "session"
      time: "14:00 - 14:50"
      name: "S. Murugensan, Z. Jiang, M. Risbeck, J. Amores, C. Zhang, V. Ramamurti, K. Drees, Y. Lee (Johnson Controls Inc)—Less is More: Simplified State-Action Space for Deep Reinforcement Learning based HVAC Control"
      
    - type: "session"
      name: "A. Naug, M. Quinones, G. Biswas (Vanderbilt University)—Continual adaptation in deep reinforcement learning-based control applied to non-stationary building environments" 
      link: "https://youtu.be/5hPpjLzJqSw"
      
    - type: "session"
      name: "D. Biagioni, X. Zhang, P. Graf, D. Sigler, W. Jones (National Renewable Energy Laboratory)—A Comparison of Model-Free and Model Predictive Control for Price Responsive Water Heaters"
      link: "https://youtu.be/yz9GaHU7lzM"
      
    - type: "session"
      name: "J. Lee, S. Huang, A. Rahman, A. Smith, S. Katipamula (Pacific Northwest National Laboratory)—Flexible Reinforcement Learning Framework for Building Control using EnergyPlus-Modelica Energy Models"
      link: "https://youtu.be/_amrG8G3pA0"
      
    - type: "session"
      name: "Discussion"
      
    - type: "session"
      time: "14:50 - 15:00"
      name: "Break"
     
    - type: "date"
      date: "Session 3: Keeping it ReaL"
      
    - type: "session"
      time: "15:00 - 15:50"
      name: "L. Spangher, A. Gokul, M. Khattar, J. Palakapilly, A. Tawade, U. Agwan, C. Spanos (University of California, Berkeley)—Augmenting Reinforcement Learning with a Planning Model for Optimizing Energy Demand Response in a Prospective Experiment"
      
    - type: "session"
      name: "X. Zhang, X. Jin, C. Tripp, D. Biagioni, P. Graf, H. Jiang (National Renewable Energy Laboratory)—Transferable Reinforcement Learning for Smart Homes"
      
    - type: "session"
      name: "A. Prakash, S. Touzani, M. Kiran, S. Agarwal, M. Pritoni, J. Granderson (Lawrence Berkeley National Laboratory)—Deep Reinforcement Learning in Buildings: Implicit Assumptions and their Impact"
      link: "https://youtu.be/roAOQRmu-_M"
      
    - type: "session"
      name: "B. Chen (Carnegie Mellon University), M. Jin (Virginia Tech), Z. Wang, T. Hong (Lawrence Berkeley National Laboratory), M. Berges (Carnegie Mellon University)—Towards Off-policy Evaluation as a Prerequisite for Real-world Reinforcement Learning in Building Control"
      link: "https://youtu.be/zlk_TDNC4qk"
      
    - type: "session"
      name: "Discussion" 
   
    - type: "session"
      time: "15:50 - 16:00"
      name: "Closing remarks"
    
    - type: "date"
      date: "Happy Hour"

  # Keynote speaker
  Speakers:
  - name: "Zico Kolter"
    url: "https://zicokolter.com/"
    affiliation: "CMU"
