baseurl: "https://rlem-workshop.net/"
title: "International Workshop on Reinforcement Learning for Energy Management in Buildings & Cities (RLEM)"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: ""

params:
  # Conference info
  Name: "First Int'l Workshop on Reinforcement Learning for Energy Management in Buildings & Cities (RLEM)"
  Description: "RLEM brings together researchers and industry practitioners for the advancement of (deep) reinforcement learning (RL) in the built environment as it is applied for managing energy in civil infrastructure systems (energy, water, transportation)."
  Date: " in November 17th 2020"
  #Price: "TBD" # If your event is free, just comment this line
  Venue: "Yokohama, Japan"
  Address: "Online"
  City:  "Yokohama"
  # State: "Quintana"
  Images: ["/img/badge.jpg"]
  GoogleMapsKey: "my-secret-maps-key"
  Registeration: "Eventbite"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - important
    - cfp
    - registration
    - program
    - speakers
    - organization
    #- sponsors
    #- partners
    #- previous
    #- contact

  # Titles which you can translate to other languages
  Titles:
    about: 
        title: "Welcome to RLEM 2020"
        abbr: "About"
    important: 
        title: "Important Dates"
    cfp: 
        title: "Call for Papers"
        abbr: "CFP"
    registration:
        title: "Registration"
    venue: 
        title: "Venue"
    speakers: 
        title: "Keynote Speaker"
        abbr: "Speaker"
    program: 
        title: "Program"
    organization: 
        title: "Organization"
    sponsors: 
        title: "Sponsors"
    partners: 
        title: "Partners"
    # contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: "Register now!"
    link: "https://www.eventbrite.com/e/rlem-workshop-2020-virtual-exact-time-tbd-tickets-121127289985"

  # List of Important Days
  Important:
    - name: "Abstract submission"
      date: "August 10, 2020 (AOE)"
      done: true 
    - name: "Paper submission"
      date: "August 17, 2020 (AOE)"
      done: true 
    - name: "Notifications"
      date: "September 21, 2020 (AOE)"
      done: true 
    - name: "Camera Ready"
      date: "October 10, 2020 (AOE)"
      done: false 
    - name: "Workshop date"
      date: "November 17, 2020"
      done: false 

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  #ForkButton:
  #  repository: "https://github.com/jweslley/hugo-conference/"

  # List of Sponsors
  Sponsors:
    - name: "Hugo"
      logo: "/img/hugo.png"
      url: "http://gohugo.io"

  # List of Partners
  Partners:
    - name: "Hugo"
      logo: "/img/hugo.jpg"
      url: "https://gohugo.io"
    - name: "BrazilJS"
      logo: "/img/partner.png"
      url: "http://braziljs.org"

  # List of Organization
  Organization:
    - role: "General"
      chair: true
      member:
        - name: "Zoltan Nagy"
          affiliation: "University of Texas at Austin"
    - role: "Technical Program Committee"
      chair: true
      member:
        - name: "Mario Berges"
          affiliation: "Carnegie Mellon University"
        - name: "Bingqing Chen"
          affiliation: "Carnegie Mellon University"
        - name: "June Young Park"
          url: "http://blog.uta.edu/parkjy/"
          affiliation: "University of Texas at Arlington"
    - role: "Technical Program Committee"
      chair: false
      member:
        - name: "Henning Lange"
          url: "https://amath.washington.edu/people/henning-lange"
          affiliation: "University of Washington"
        - name: "Helia Zandi"
          url: "https://www.ornl.gov/staff-profile/helia-zandi"
          affiliation: "Oak Ridge National Laboratory"
        - name: "Jose Vazquez-Canteli"
          url: "http://nagy.caee.utexas.edu"
          affiliation: "University of Texas at Austin" 
        - name: "Zhe Wang"
          url: "https://buildings.lbl.gov/people/zhe-walter-wang"
          affiliation: "Lawrence Berkeley National Laboratory"
        - name: "Duc Van Le"
          url: ""
          affiliation: "NTU Singapore"
        - name: "Wan Du"
          url: ""
          affiliation: "University of California, Merced"
        - name: "Xin Jin"
          url: ""
          affiliation: "National Renewable Energy Laboratory"
        - name: "Ming Jin"
          url: ""
          affiliation: "University of California, Berkeley"
        - name: "Alex Vlachokostas"
          url: ""
          affiliation: "Pacific Northwest National Laboratory"
        - name: "Hari Prasanna Das"
          url: ""
          affiliation: "University of California, Berkeley"
        - name: "Lucas Spangheer"
          url: ""
          affiliation: "University of California, Berkeley"
        - name: "Kuldeep Kurte"
          url: ""
          affiliation: "Oak Ridge National Laboratory"
        - name: "Ross May"
          url: ""
          affiliation: "Dalarna University"
 #       - name: ""
 #         url: ""
 #         affiliation: ""
          
  # The entire program 
  Program:
    - type: "date"
      date: "TBD"

    - type: "session"
      time: "12:00 - 12:10"
      name: "Opening remarks, General Chair"
   
    - type: "session"
      time: "12:10 - 12:20"
      name: "Introduction, TPC Chairs"
      
    - type: "session"
      time: "12:20 - 13:00"
      name: "Keynote: Incorporating robust control guarantees within (deep) reinforcement learning"
     

  # Keynote speaker
  Speakers:
  - name: "Zico Kolter"
    url: "https://zicokolter.com/"
    affiliation: "CMU"
