baseurl: "https://rlem-workshop.net/"
title: "ACM SIGEnergy Workshop on Reinforcement Learning for Energy Management in Buildings & Cities (RLEM)"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: ""

params:
  # Conference info
  Name: "Second ACM SIGEnergy Workshop on Reinforcement Learning for Energy Management in Buildings & Cities (RLEM)"
  Description: "RLEM brings together researchers and industry practitioners for the advancement of (deep) reinforcement learning (RL) in the built environment as it is applied for managing energy in civil infrastructure systems (energy, water, transportation)."
  Date: " in November 17th 2021"
  #Price: "TBD" # If your event is free, just comment this line
  Venue: "Coimbra, Portugal"
  Address: "Hybrid"
  City:  "Coimbra"
  # State: "Quintana"
  Images: ["/img/badge.jpg"]
  GoogleMapsKey: "my-secret-maps-key"
  Registeration: "Eventbite"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - important
    - cfp
    - registration
    - program
    - speakers
    - organization
    #- sponsors
    #- partners
    #- previous
    #- contact

  # Titles which you can translate to other languages
  Titles:
    about:
        title: "Welcome to RLEM 2021"
        abbr: "About"
    important:
        title: "Important Dates"
    cfp:
        title: "Call for Papers"
        abbr: "CFP"
    registration:
        title: "Registration"
    venue:
        title: "Venue"
    speakers:
        title: "Keynote Speaker"
        abbr: "Speaker"
    program:
        title: "Program"
    organization:
        title: "Organization"
    sponsors:
        title: "Sponsors"
    partners:
        title: "Partners"
    # contact: "Contact"
    #previous:
    #    title: "Past RLEM"
    #    abbr: "Past"
  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: "Register now via BuildSys 2021!"
    link: "http://buildsys.acm.org/2021/"

  # List of Important Days
  Important:
    - name: "Abstract submission"
      date: "September 6, 2021 (AOE)"
      done: false
    - name: "Paper submission"
      date: "September 6, 2021 (AOE)"
      done: false
    - name: "Notifications"
      date: "September 27, 2021 (AOE)"
      done: false
    - name: "Camera Ready"
      date: "October 1, 2021 (AOE)"
      done: false
    - name: "Workshop date"
      date: "TBD" #"November 17, 2021"
      done: false
  # List of Previous Editions
  Previous:
    - name: "RLEM 2020"
      url: "https://rlem-workshop.net/2020/"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  #ForkButton: repository: "https://github.com/jweslley/hugo-conference/"

  # List of Sponsors
  Sponsors:
    - name: "Hugo"
      logo: "/img/hugo.png"
      url: "http://gohugo.io"

  # List of Partners
  Partners:
    - name: "Hugo"
      logo: "/img/hugo.jpg"
      url: "https://gohugo.io"
    - name: "BrazilJS"
      logo: "/img/partner.png"
      url: "http://braziljs.org"

  # List of Organization
  Organization:
    - role: "General"
      chair: true
      member:
        - name: "Zoltan Nagy"
          affiliation: "University of Texas at Austin"
    - role: "Technical Program Committee"
      chair: true
      member:
        - name: "Jan Drgona"
          url: "https://www.pnnl.gov/people/jan-drgona"
          affiliation: "Pacific Northwest National Laboratory"
        - name: "June Young Park"
          url: "http://blog.uta.edu/parkjy/"
          affiliation: "University of Texas at Arlington"
    - role: "Web"
      chair: True
      member:
        - name: "Matias Quintana"
          url: "https://matiasquintana.com/"
          affiliation: "National University of Singapore"
    - role: "Technical Program Committee"
      chair: false
      member:
        - name: "Anand Krishnan Prakash"
          url: "https://eta.lbl.gov/people/anand-krishnan-prakash"
          affiliation: "Lawrence Berkeley National Lab"
        - name: "Anjukan Kathirgamanathan"
          url: "https://anjukan.github.io/about/"
          affiliation: "University College Dublin"
        - name: "Ankush Chakrabarty"
          url: "https://www.merl.com/people/chakrabarty"
          affiliation: "MERL - Mitsubishi Electric Research Laboratories"
        - name: "Bharathan Balaji"
          url: "https://www.amazon.science/author/bharathan-balaji"
          affiliation: "Amazon"
        - name: "Bratislav Svetozarevic"
          url: "https://www.empa.ch/web/svb"
          affiliation: "Swiss Federal Laboratories for Materials Science and Technology"
        - name: "Giuseppe Pinto"
          url: "https://www.denerg.polito.it/en/personale/scheda/(nominativo)/giuseppe-pinto"
          affiliation: "Politecnico di Torino"
        - name: "Hari Prasanna Das"
          url: "http://hariprasanna.com/"
          affiliation: "UC Berkeley"
        - name: "Helia Zandi"
          url: "https://www.ornl.gov/staff-profile/helia-zandi"
          affiliation: "Oak Ridge National Laboratory"
        - name: "Jose Vazquez-Canteli"
          url: "https://onboarddata.io/about"
          affiliation: "Onboard Data"
        - name: "Kuldeep Kurte"
          url: "https://www.ornl.gov/staff-profile/kuldeep-r-kurte"
          affiliation: "Oak Ridge National Laboratory"
        - name: "Matias Quintana"
          url: "https://matiasquintana.com/"
          affiliation: "National University of Singapore"
        - name: "Ming Jin"
          url: "https://ece.vt.edu/people/profile/jinming"
          affiliation: "Virginia Tech"
        - name: "Omid Ardakanian"
          url: "https://webdocs.cs.ualberta.ca/~oardakan/"
          affiliation: "University of Alberta"
        - name: "Silvio Brandi"
          url: "https://www.denerg.polito.it/en/personale/scheda/(nominativo)/silvio.brandi"
          affiliation: "Politecnico di Torino"
        - name: "Xin Jin"
          url: "https://www.nrel.gov/research/staff/xin-jin.html"
          affiliation: "National Renewable Energy Laboratory"
        - name: "Zhe Wang"
          url: "https://buildings.lbl.gov/people/zhe-walter-wang"
          affiliation: "Lawrence Berkeley National Lab"
        - name: "Zhiang Zhang"
          url: "https://www.nottingham.edu.cn/en/Science-Engineering/People/Profile.aspx?id=bddcf982-feb9-4173-bc78-87554ca6657f&language=en-GB"
          affiliation: "University of Nottingham Ningbo China"

  # The entire program
  Program:
    - type: "session"
      time: "15:00 - 15:20"
      name: "Opening remarks, by General Chair and TPC Chairs"

    - type: "session"
      time: "15:20 - 16:00"
      name: "1st Keynote: Gregor Henze (University of Colorado Boulder)"

    - type: "session"
      time: "16:00 - 16:50"
      name: "Session 1: Addressing challenges of applying RL in real-world buildings"

    - type: "session"
      time: "16:50 - 17:00"
      name: "Break"

    - type: "session"
      time: "17:00 - 17:40"
      name: "2nd Keynote: Helia Zandi (Oak Ridge National Laboratory)"

    - type: "session"
      time: "17:40 - 18:00"
      name: "Community Announcements"

    - type: "session"
      time: "18:00 - 18:50"
      name: "Session 2: Benchmarking RL with other controls including other RLs"

    - type: "session"
      time: "18:50 - 19:00"
      name: "Break"

    - type: "session"
      time: "19:00 - 20:20"
      name: "Session 3: Testing environment"

    - type: "session"
      time: "20:20 - 20:30"
      name: "Closing remarks"

  # Keynote speaker
  Speakers:
    - name: "Helia Zandi"
      url: "https://www.ornl.gov/staff-profile/helia-zandi"
      affiliation: "Oak Ridge National Lab"
      photo: "/img/helia_zandi.jpg"
    - name: "Gregor Henze"
      url: "https://www.colorado.edu/ceae/gregor-p-henze"
      affilitation: "CU Boulder"
      photo: "/img/gregor_henze.png"
